[tool.poetry]
name = "learning-langchain"
version = "0.1.0"
description = ""
authors = ["Koichiro Mori <f2forest@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.2.14"
langchain-openai = "^0.1.21"
ipykernel = "^6.29.5"
langserve = {extras = ["all"], version = "^0.2.2"}
langchain-community = "^0.2.12"
langchain-chroma = "^0.1.2"
beautifulsoup4 = "^4.12.3"
langchain-anthropic = "^0.1.23"
langgraph = "^0.2.4"
youtube-transcript-api = "^0.6.2"
pytube = "^15.0.0"
ipywidgets = "^8.1.3"
faiss-cpu = "^1.8.0.post1"
langchain-google-genai = "^1.0.10"
langchain-google-firestore = "^0.3.0"
langchain-google-community = "^1.0.8"
google-cloud-discoveryengine = "^0.12.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
